server {
	listen 443 ssl;
	ssl_protocols TLSv1.2 TLSv1.3;
	server_name dsatge.42.fr;
	ssl_certificate /etc/nginx/ssl/inception.crt;
	ssl_certificate_key /etc/nginx/ssl/inception.key;
	root /var/www/html/;
	index index.php index.html index.htm;
	location / {
		try_files $uri/ =404;
	}

	location ~ \.php$ {
		include fastcgi_params;
		# split path from other arguments : avoid malicious commands in Path
		fastcgi_split_path_info ^(.+\.php)(/.+)$;
		# adress to send PHP content
		fastcgi_pass wordpress:9000;
		# gives default file to search if folder needed
		fastcgi_index index.php;

		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
		fastcgi_param PATH_INFO $fastcgi_path_info;
	}
}