
services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - inception_network
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "$SQL_USER", "-p$SQL_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 10

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - inception_network
    volumes:
      - wordpress_data:/var/www/html

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx
    restart: unless-stopped
    depends_on:
       - wordpress
    ports:
      - "443:443"
    networks:
      - inception_network
    volumes:
      - wordpress_data:/var/www/html

networks:
  inception_network:
    name: Inception
    driver: bridge

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_PATH}/mariadb
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_PATH}/wordpress
